project:
  type: website

website:
  title: "Bode Plot Generator"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resources.qmd
        text: Resources
      - href: fpga.qmd
        text: FPGA
      - href: mcu.qmd
        text: MCU
      - href: system.qmd
        text: System Integration
      - href: demo.qmd
        text: Demo and Results
      - href: about.qmd
        text: About

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true